import type { Metadata } from "next";
import "./globals.css";
import { Oswald } from 'next/font/google'
import Main from "./components/Main";

const oswald = Oswald({
  weight: ['400', "500", '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} antialiased`}
      >
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
